services:
    # Servicio 1: Base de Datos
    db:
        image: postgres:15-alpine
        container_name: pos-db-docker
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5433:5432" # Puerto externo 5433 para que no choque con el Postgres local
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - pos-network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5

    # Servicio 2: Backend
    app:
        container_name: pos-backend-app
        build: ./backend
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
            - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
            - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRATION=${JWT_EXPIRATION}

            # CORS
            - APP_CORS_ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost}

            # Admin Inicial (DataSeeder)
            - ADMIN_USERNAME=${ADMIN_USER}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}

            - APP_TIME_ZONE=${APP_TIME_ZONE}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - pos-network

    # Servicio 3: Wbe/Frontend (Nginx + Angular)
    web:
        container_name: pos-frontend-web
        build:
            context: ./frontend # Contexto = carpeta frontend
            dockerfile: Dockerfile
        ports:
            - "80:80" # El usuario final entra por aquí
        depends_on:
            - app
        networks:
            - pos-network

volumes:
    postgres_data:


networks:
    pos-network:
        driver: bridge
