version: '3.8'

services:
    # Servicio 1: La Base de Datos (Aislada en contenedor)
    db:
        image: postgres:15-alpine
        container_name: pos-db-docker
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin # Puedes cambiarla si quieres
            POSTGRES_DB: db_pos
        ports:
            - "5433:5432" # Expone el puerto (Cuidado si tienes el local corriendo, chocarán)
        volumes:
            - postgres_data:/var/lib/postgresql/data # Persistencia de datos

    # Servicio 2: Tu Backend
    app:
        container_name: pos-backend-app
        build: . # Usa el Dockerfile de la carpeta actual
        ports:
            - "8080:8080"
        environment:
            # OJO: Aquí 'db' es el nombre del servicio de arriba. Docker resuelve la IP solo.
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_pos
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=admin
        depends_on:
            - db # Espera a que la BD inicie antes de arrancar la app

volumes:
    postgres_data: # Define el volumen para guardar los datos
