# "optional:" hace que no falle si el archivo no existe (ej. en producción en la nube)
spring.config.import=optional:file:.env[.properties]

spring.application.name=POS System
# --- CONEXIÓN A BASE DE DATOS ---
spring.datasource.url=jdbc:postgresql://localhost:5432/db_pos
spring.datasource.username=postgres
# ¡CAMBIA ESTO POR TU CONTRASEÑA REAL!
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- COMPORTAMIENTO JPA ---
# "update": Si agregas un campo en Java, actualizará la tabla automáticamente.
# Es lo mejor para desarrollo rápido sin borrar tus datos.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- RUTA BASE DE LA API ---
server.servlet.context-path=/api/v1