# --- COMPORTAMIENTO JPA PARA PRODUCCIÓN ---
# "validate": Valida el esquema, no hace cambios a la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=validate

# No mostrar SQL en logs de producción para evitar Information Disclosure y saturación
spring.jpa.show-sql=false

# Ocultar trazas de errores completos al cliente
server.error.include-stacktrace=never
app.debug=false

# Deshabilitar Swagger/OpenAPI en producción por seguridad
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
