name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Get GitHub Runner IP
      id: ip
      run: echo "ipv4=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Whitelist Runner IP
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.AWS_SG_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.2.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # 1. Navegar a la carpeta del proyecto
          cd pos-enterprise-system
          
          # 2. Bajar los últimos cambios de GitHub
          git pull origin main
          
          # 3. Reconstruir y reiniciar contenedores
          # Usamos --build para asegurar que si cambiaste Java/Angular, se recompilen
          docker-compose up -d --build
          
          # 4. Limpieza (Opcional): Borrar imágenes viejas para no llenar el disco
          docker image prune -f

    - name: Revoke Runner IP
      if: always()
      run: |
        aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.AWS_SG_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32