name: Deploy via AWS SSM (Zero Trust)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Execute Deploy Command via SSM
      run: |
        echo "Iniciando despliegue en la instancia ${{ secrets.EC2_INSTANCE_ID }}..."
        
        # Enviamos el comando y capturamos el ID de la operación
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=${{ secrets.EC2_INSTANCE_ID }}" \
          --comment "Despliegue automático GitHub Actions" \
          --parameters 'commands=["cd /home/ubuntu/pos-enterprise-system", "git pull origin main", "docker compose up -d --build", "docker image prune -f"]' \
          --output text \
          --query "Command.CommandId")

        echo "Comando enviado con éxito. ID: $COMMAND_ID"
        echo "Esperando confirmación de ejecución..."
        
        # Esperamos a que el servidor termine de procesar (Éxito o Fallo)
        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
        
        # (Opcional) Mostramos el resultado final en el log de GitHub
        echo "Resultado del despliegue:"
        aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
          --query "StandardOutputContent" \
          --output text